name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Odin
      run: |
        git clone https://github.com/odin-lang/Odin.git
        pushd Odin
        make release
        popd
    - name: Build
      run: ./Odin/odin build .
